authentication flow: sigup, login and logout functionality added
Tramchandani/gym-management-system pull request #1
Opened 2021-03-11 06:52 UTC by Tramchandani

![Screenshot from 2021-03-11 12-18-44](https://user-images.githubusercontent.com/79201195/110747326-3a37ad80-8264-11eb-8e38-a24fa555cce6.png)
![Screenshot from 2021-03-11 12-19-57](https://user-images.githubusercontent.com/79201195/110747336-3d329e00-8264-11eb-8226-b8ff2dee6b37.png)
![Screenshot from 2021-03-11 12-20-05](https://user-images.githubusercontent.com/79201195/110747340-3efc6180-8264-11eb-945a-10f373e060f0.png)
![Screenshot from 2021-03-11 12-20-22](https://user-images.githubusercontent.com/79201195/110747346-40c62500-8264-11eb-9175-ab8d1ab4928c.png)

2021-03-11 08:01 UTC, kalpana19sharma requested changes

2021-03-11 08:01 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +  end
Use single line syntax for empty methods.
```suggestion
  def index; end
```

2021-03-11 08:01 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +  end
By the way why do we need index action?

2021-03-11 08:01 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    @user = User.create(signup_params)
This will already insert the record in database then what's the need to call `save`?

2021-03-11 08:01 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    session[:user_id] = @user.id
You should only set this session if the user is successfully created.

2021-03-11 08:01 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +      redirect_to user_path(@user.id)
Set flash message

2021-03-11 08:01 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +  end
There should be a separate controller for session management. Users controller should only have responsibility related to user CRUD operations.

2021-03-11 08:01 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +
Remove unnecessary empty line.

2021-03-11 08:01 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    if user && user.authenticate(params[:password])
1. Use strong parameters
2. Use `&.` operator.

2021-03-11 08:01 UTC, kalpana19sharma commented on app/models/user.rb
> +end
Can we find some other alternative?

2021-03-11 08:01 UTC, kalpana19sharma commented on app/models/user.rb
> +  #validates_with Regex
Fix indentation and I think you have lot of unnecessary code in this file.

2021-03-11 08:01 UTC, kalpana19sharma commented on app/views/users/index.html.erb
> +
Fix indentattion

2021-03-11 08:01 UTC, kalpana19sharma commented on app/views/users/login.html.erb
> +<%= form_with :url => {:action => 'authenticate'}, method: :get do %>
Don't use `=>` syntax

2021-03-11 08:01 UTC, kalpana19sharma commented on app/views/users/show.html.erb
> +</p>
Use proper indentation

2021-03-11 08:01 UTC, kalpana19sharma commented on app/views/users/signup.html.erb
> +-->
Extract this logic in a partial and remove commented code.

2021-03-11 08:01 UTC, kalpana19sharma commented on app/views/users/signup.html.erb
> +  <% end %>
This logic is repeating. Refactor your logic.

2021-03-11 08:01 UTC, kalpana19sharma commented on config/database.yml
> +  #password: password
Don't commit the passwords.

2021-03-11 08:01 UTC, kalpana19sharma commented on config/database.yml
> +  #password: password
Refer this: https://blog.saeloun.com/2019/10/10/rails-6-adds-support-for-multi-environment-credentials.html

2021-03-11 08:01 UTC, kalpana19sharma commented on config/routes.rb
> +  resources :users
You are generating some unnecessary routes.

2021-03-11 08:05 UTC, Tramchandani commented on app/controllers/users_controller.rb
> +  end
Index page is the first page where the login and signup option is displayed
So to render index.html.erb I have made this method

2021-03-12 10:13 UTC, kalpana19sharma requested changes
@Tramchandani your PR has a lot of indentation and code styling issues. Please fix those, don't use `=>` syntax and remove byebug/commented code

2021-03-12 10:13 UTC, kalpana19sharma commented on app/helpers/application_helper.rb
> +      if !object.errors.messages[field].blank?
Use `unless`

2021-03-12 10:13 UTC, kalpana19sharma commented on app/models/user.rb
> +  regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
Make it a constant

2021-03-12 10:13 UTC, kalpana19sharma commented on app/models/user.rb
>    validates :email, uniqueness: { case_sensitive: false}, format: { with: regex}
Use proper spaces

2021-03-12 10:13 UTC, kalpana19sharma commented on app/views/layouts/_display_error.html.erb
> +  <% end %>
Fix indentation

2021-03-12 10:13 UTC, kalpana19sharma commented on app/views/sessions/login.html.erb
> +  <%= text_field_tag :email %>
Use `email_field_tag`

2021-03-12 10:13 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    @user = User.create(signup_params)
Not handled

2021-03-12 10:13 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +
No handled

2021-03-13 12:06 UTC, kalpana19sharma requested changes

2021-03-13 12:06 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +      redirect_to root_url
You should keep the user on the same form if the login fails.

2021-03-13 12:06 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +  def create
Add an empty line above method definition.

2021-03-13 12:06 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +  def show
Add an empty line above method definition.

2021-03-13 12:06 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +  def signup_params
Add an empty line above method definition.

2021-03-13 12:06 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    params.require(:user).permit(:first_name, :last_name,:dob, :email, :password, :password_confirmation)
Add proper spaces

2021-03-13 12:06 UTC, kalpana19sharma commented on app/models/user.rb
> +  validates :password, confirmation: true
Combine password validations.

2021-03-13 12:06 UTC, kalpana19sharma commented on app/models/user.rb
> +end
Add a new line at the end of the file.

2021-03-13 12:06 UTC, kalpana19sharma commented on app/views/layouts/_display_error.html.erb
> +<% end %>
Add a new line at the end of the file.

2021-03-13 12:06 UTC, kalpana19sharma commented on app/views/users/login.html.erb
> +  <%= text_field_tag :email %>
Use email field.

2021-03-13 12:06 UTC, kalpana19sharma commented on app/views/users/login.html.erb
> +<%= link_to "back", login_path %>
Add new line at the end of the file.

2021-03-13 12:06 UTC, kalpana19sharma commented on app/views/users/new.html.erb
> +  <%= form.text_field :email %>
Use email field

2021-03-13 12:06 UTC, kalpana19sharma commented on app/views/users/show.html.erb
> +
Remove extra empty line.

2021-03-13 12:06 UTC, kalpana19sharma commented on config/database.yml
> +  password: password
Don't add passwords in the code.

2021-03-13 12:06 UTC, kalpana19sharma commented on config/routes.rb
> +  get 'sessions/authenticate', to: 'sessions#authenticate', as: 'authenticate'
This should be post type route

2021-03-13 12:06 UTC, kalpana19sharma commented on config/routes.rb
> +  resources :users, only: [:create, :new, :show]
Use `%i` syntax for array of symbols

2021-03-13 12:06 UTC, kalpana19sharma commented on app/views/users/login.html.erb
> +<h1>Login Page</h1>
You have 2 login forms?

2021-03-13 14:21 UTC, Tramchandani commented on config/database.yml
> +  password: password
ma'am the process of support for credentials is not very clear, I tried the steps given in the link but they did not work as mentioned that's why I did not encrypt the password.

2021-03-13 14:27 UTC, Tramchandani commented on config/routes.rb
> +  get 'sessions/authenticate', to: 'sessions#authenticate', as: 'authenticate'
ma'am there are no changes being done in the database, so why should it be post type?

2021-03-13 14:31 UTC, Tramchandani commented on app/views/users/login.html.erb
> +<h1>Login Page</h1>
ma'am earlier I made login a part of user controller and then shifted it to sessions controller so I forgot to delete the login file of user controller hence this file. It is not being used anywhere. I'll delete it right away.

2021-03-13 15:19 UTC, kalpana19sharma commented on config/routes.rb
> +  get 'sessions/authenticate', to: 'sessions#authenticate', as: 'authenticate'
Because get request is only used to fetch some data and no to set/insert something. In this case we are setting session value. And also we are submitting a form and generally form submission use post/put/patch request.

2021-03-13 15:19 UTC, kalpana19sharma commented on config/database.yml
> +  password: password
Maybe explore `figaro` gem

2021-03-14 14:58 UTC, kalpana19sharma requested changes

2021-03-14 14:58 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +    if user&.authenticate(params[:password])
Use strong parameters for password as well. Define a separate method for strong parameters.

2021-03-14 14:58 UTC, kalpana19sharma commented on app/models/user.rb
> +
remove this extra line.

2021-03-15 06:37 UTC, kalpana19sharma requested changes

2021-03-15 06:37 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +  end
Combine these method in a single method

2021-03-15 07:59 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +  end
```suggestion
  def session_params
    params.permit(:email, :password)
  end
```

2021-03-15 08:00 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +  end
And then use `session_params[:email]` and `session_params[:password]`

2021-03-15 08:32 UTC, kalpana19sharma approved these changes

2021-03-15 08:33 UTC, merged