bootstrap integration
Tramchandani/gym-management-system pull request #2
Opened 2021-03-15 06:38 UTC by Tramchandani

![Screenshot from 2021-03-15 12-05-04](https://user-images.githubusercontent.com/79201195/111113003-1687a680-8587-11eb-8c1e-788c94020b8f.png)
![Screenshot from 2021-03-15 12-05-52](https://user-images.githubusercontent.com/79201195/111113008-18ea0080-8587-11eb-8253-bb0e3c8cfbc2.png)
![Screenshot from 2021-03-15 12-06-04](https://user-images.githubusercontent.com/79201195/111113014-1a1b2d80-8587-11eb-8d91-c3df052a84b9.png)
![Screenshot from 2021-03-15 12-06-09](https://user-images.githubusercontent.com/79201195/111113020-1c7d8780-8587-11eb-9b0d-aa804206072d.png)

2021-03-15 08:31 UTC, kalpana19sharma commented
@Tramchandani please resolve all of the conflicts and also your form elements are not properly aligned, if possible please fix that. If its taking too much time, you can skip for now.

2021-03-15 09:39 UTC, kalpana19sharma requested changes

2021-03-15 09:39 UTC, kalpana19sharma commented on app/assets/stylesheets/custom.css.scss
> +body,html {
Use proper spaces

2021-03-15 09:39 UTC, kalpana19sharma commented on app/assets/stylesheets/custom.css.scss
> +.bg{
Use proper spaces

2021-03-15 09:39 UTC, kalpana19sharma commented on app/assets/stylesheets/custom.css.scss
> +
Remove extra empty line

2021-03-15 09:39 UTC, kalpana19sharma commented on app/assets/stylesheets/custom.css.scss
> +}
Add newline at the end of the file.

2021-03-15 09:39 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    else
Remove whitespace

2021-03-15 09:39 UTC, kalpana19sharma commented on app/views/sessions/index.html.erb
> +  <% if session[:user_id] %>
Instead of just checking user_id present or not. You should check if the user corresponding to this user_id present or not.

2021-03-15 09:39 UTC, kalpana19sharma commented on app/views/sessions/index.html.erb
> +    </br>
its not a best practice to use `br` tag

2021-03-15 09:39 UTC, kalpana19sharma commented on app/views/sessions/index.html.erb
> +</div>
This logic is used in multiple view file. Extract this in partial

2021-03-15 09:39 UTC, kalpana19sharma commented on config/database.yml
> +  password: <%= ENV["PASSWORD"] %>
Add new line.

2021-03-15 09:39 UTC, kalpana19sharma commented on config/webpack/environment.js
> +}))
Fix indentation

2021-03-15 10:26 UTC, Tramchandani commented on app/views/sessions/index.html.erb
> +    </br>
what should be used instead?

2021-03-15 10:29 UTC, Tramchandani commented on app/views/sessions/index.html.erb
> +  <% if session[:user_id] %>
If the user navigates to the login page there should be no current user_id, that is no one should be logged in so how to check if the session id corresponds to the current user since it's not supposed to exist?

2021-03-15 10:35 UTC, kalpana19sharma commented on app/views/sessions/index.html.erb
> +  <% if session[:user_id] %>
Okay let me reframe: check presence of user along with session[:user_id]

2021-03-15 10:36 UTC, kalpana19sharma commented on app/views/sessions/index.html.erb
> +    </br>
Use bootstrap classes or custom css

2021-03-15 15:07 UTC, kalpana19sharma requested changes

2021-03-15 15:07 UTC, kalpana19sharma commented on app/views/layouts/_show_notice.html.erb
> +<% end %>
Add new line

2021-03-15 15:07 UTC, kalpana19sharma commented on app/helpers/application_helper.rb
> +  def check_user?(user_id)
What's the need of `user_id` parameter

2021-03-15 15:07 UTC, kalpana19sharma commented on config/database.yml
> +
Properly manage extra lines

2021-03-15 16:54 UTC, Tramchandani commented on config/database.yml
> +
extra lines as in the commented out code?

2021-03-16 04:45 UTC, kalpana19sharma commented on config/database.yml
> +
Extra empty lines at the end of the file.

2021-03-17 02:59 UTC, kalpana19sharma approved these changes

2021-03-17 02:59 UTC, merged