User profile
Tramchandani/gym-management-system pull request #4
Opened 2021-03-17 08:52 UTC by Tramchandani

![Screenshot from 2021-03-17 14-21-40](https://user-images.githubusercontent.com/79201195/111440189-1e348000-872c-11eb-8220-5b94f8813cc4.png)
![Screenshot from 2021-03-17 14-21-36](https://user-images.githubusercontent.com/79201195/111440198-2096da00-872c-11eb-92e4-cbfbfcc3e4f2.png)
![Screenshot from 2021-03-17 14-21-31](https://user-images.githubusercontent.com/79201195/111440206-22609d80-872c-11eb-9c0e-40525364e5e2.png)

2021-03-18 05:25 UTC, kalpana19sharma commented
@Tramchandani please resolve the conflicts.

2021-03-19 08:18 UTC, kalpana19sharma requested changes

2021-03-19 08:18 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    @user = current_user
Use a before action filter to set `@user`

2021-03-19 08:18 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    flash[:notice] = "updating profile"
What's the need for this?

2021-03-19 08:18 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    if @user&.authenticate(password_params[:current_password]) && @user.update(password: password_params[:password], password_confirmation: password_params[:password_confirmation])
Line is too long.

2021-03-19 08:18 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    @user = current_user
This line of code is repetitive

2021-03-19 08:18 UTC, kalpana19sharma commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css" %>
Don't use the cdn url for bootstrap. We are going to integrate package for bootstrap.

2021-03-19 08:18 UTC, kalpana19sharma commented on app/views/users/edit.html.erb
> +</div>
add new line

2021-03-19 08:18 UTC, kalpana19sharma commented on app/views/users/edit_password.html.erb
> +  <%= form_for :user_pass , url: :update_password do |form| %>
is it correct? `url: :update_password`

2021-03-19 10:28 UTC, Tramchandani commented on app/controllers/users_controller.rb
> +    flash[:notice] = "updating profile"
ma'am I added it for debugging purpose.
I will remove it now

2021-03-19 11:11 UTC, Tramchandani commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css" %>
ma'am how do we integrate specific urls through bootstrap package?

2021-03-19 12:18 UTC, kalpana19sharma commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css" %>
yes

2021-03-20 02:53 UTC, kalpana19sharma requested changes

2021-03-20 02:53 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +  skip_before_action :current_user, only: [:new, :create]
Can we combine these 2 lines.

2021-03-20 02:53 UTC, kalpana19sharma commented on app/models/user.rb
> +  def updating_profile?
Rename this method to `should_validate_password?`

2021-03-20 02:53 UTC, kalpana19sharma commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" %>
Remove this URL in bootstrap PR

2021-03-20 03:42 UTC, kalpana19sharma commented on app/models/user.rb
> +  def updating_profile?
Also what should be the access level of this method?

2021-03-20 09:47 UTC, Tramchandani commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" %>
ma'am I have tried using bootstrap classes and they are working fine but yet if I am removing this link the UI gets distorted.
I tried different things to fix it by integrating bootstrap again in different ways but still it's not working properly.

2021-03-20 10:19 UTC, Tramchandani commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" %>
I even tried adding a feature from bootstrap 4 documentation and it is working fine but there seems to be some issue with the one I am currently using.
Should I use some other bootstrap code for the page or try something else?

2021-03-21 04:42 UTC, kalpana19sharma commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" %>
I think this link is including bootstrap 3. If this can be the issue?

2021-03-21 04:44 UTC, kalpana19sharma requested changes

2021-03-21 04:44 UTC, kalpana19sharma commented on app/models/user.rb
> +  end
Fix indentation

2021-03-21 10:23 UTC, Tramchandani commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" %>
Yes I think that's the issue. Maybe bootstrap 4 does not support some of the classes of bootstrap 3 and I might have used them in my code. So is there a way to add support for bootstrap 3 as well as 4 in the application?

2021-03-22 01:18 UTC, kalpana19sharma commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" %>
I don't think so. Let's move to bootstrap 4

2021-03-22 11:38 UTC, kalpana19sharma requested changes

2021-03-22 11:38 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    render layout: 'empty'
Why do we need a different layout?

2021-03-22 11:38 UTC, kalpana19sharma commented on app/views/layouts/_sidebar.html.erb
> +        <% end %>
Use proper spaces and check all occurrences

2021-03-22 11:38 UTC, kalpana19sharma commented on app/views/layouts/_sidebar.html.erb
> +
Remove extra line

2021-03-22 11:38 UTC, kalpana19sharma commented on app/views/users/edit.html.erb
> +
Remove extra line

2021-03-22 11:38 UTC, kalpana19sharma commented on app/views/users/show.html.erb
> +
Remove extra line

2021-03-22 11:56 UTC, Tramchandani commented on app/controllers/users_controller.rb
> +    render layout: 'empty'
In application.html.erb I have center aligned all the elements.
But to display user profile I had to display info in a larger area hence the different layout.

2021-03-22 14:16 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    render layout: 'empty'
ok

2021-03-23 04:42 UTC, Tramchandani commented on app/views/layouts/_sidebar.html.erb
> +        <% end %>
all occurances as in?

2021-03-23 10:44 UTC, kalpana19sharma approved these changes

2021-03-23 10:44 UTC, merged