Active storage
Tramchandani/gym-management-system pull request #5
Opened 2021-03-18 11:19 UTC by Tramchandani

![Screenshot from 2021-03-18 16-48-16](https://user-images.githubusercontent.com/79201195/111617997-dd129d80-8809-11eb-8ebe-39da66bb5617.png)
![Screenshot from 2021-03-18 16-48-25](https://user-images.githubusercontent.com/79201195/111618003-df74f780-8809-11eb-81b2-943e2bb5c2ab.png)
![Screenshot from 2021-03-18 16-48-34](https://user-images.githubusercontent.com/79201195/111618011-e13ebb00-8809-11eb-8597-4369efc4dcce.png)
![Screenshot from 2021-03-18 16-48-39](https://user-images.githubusercontent.com/79201195/111618021-e26fe800-8809-11eb-8ca6-e1aade814739.png)

2021-03-20 03:49 UTC, kalpana19sharma requested changes

2021-03-20 03:49 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    @user = current_user
Use before action filter.

2021-03-20 03:49 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    flash[:notice] = "updating profile"
What's this for?

2021-03-20 03:49 UTC, kalpana19sharma commented on app/assets/stylesheets/sidebar.css
> +}
Don't write unnecessary code.

2021-03-20 03:49 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    @image =  ActiveStorage::Blob.find_signed(img_params[:id])
What does `find_signed` do?

2021-03-20 17:30 UTC, Tramchandani commented on app/controllers/users_controller.rb
> +    @user = current_user
ma'am I already made this change in user profile branch but since this branch was made from user profile branch and I submitted this PR before review of user profile hence it is repetitive here.

2021-03-20 17:34 UTC, Tramchandani commented on app/controllers/users_controller.rb
> +    flash[:notice] = "updating profile"
ma'am same for this as well I have made these changes for user profile branch

2021-03-20 18:50 UTC, Tramchandani commented on app/controllers/users_controller.rb
> +    @image =  ActiveStorage::Blob.find_signed(img_params[:id])
ma'am I searched for deletion of image so this was the method that I found for fetching an image id

2021-03-23 10:57 UTC, kalpana19sharma commented
@Tramchandani Please resolve the conflicts.

2021-03-23 12:03 UTC, kalpana19sharma requested changes

2021-03-23 12:03 UTC, kalpana19sharma commented on app/javascript/packs/custom.js
> +
Fix indentation and remove extra line.

2021-03-23 12:03 UTC, kalpana19sharma commented on app/models/user.rb
> +
Remove white-space.

2021-03-23 12:03 UTC, kalpana19sharma commented on app/views/layouts/_sidebar.html.erb
> +</div>
new line

2021-03-23 12:03 UTC, kalpana19sharma commented on app/views/layouts/_sidebar.html.erb
> +        <%= link_to all_images_path(session[:user_id]) do%>
Use proper spaces

2021-03-23 12:03 UTC, kalpana19sharma commented on app/views/layouts/_sidebar.html.erb
> +        <%= link_to logout_path do%>
Use proper spaces

2021-03-23 12:03 UTC, kalpana19sharma commented on app/views/layouts/empty2.html.erb
> +</html>
What's the need for this?

2021-03-23 12:03 UTC, kalpana19sharma commented on app/views/layouts/empty2.html.erb
> +</html>
Can't we use `empty`?

2021-03-23 12:03 UTC, kalpana19sharma commented on app/views/users/add_image.html.erb
> +</div>
new line

2021-03-23 12:03 UTC, kalpana19sharma commented on app/views/users/all_images.html.erb
> +
Remove extra line.

2021-03-23 12:03 UTC, kalpana19sharma commented on app/views/users/show.html.erb
> +                <%= image_tag @user.images.last, class: "rounded-circle dimensions"%>
Use proper spaces

2021-03-23 12:03 UTC, kalpana19sharma commented on config/routes.rb
> +  get 'users/all_images/:id', to: 'users#all_images', as: 'all_images'
```suggestion
  get 'users/images/:id', to: 'users#all_images', as: 'all_images'
```

2021-03-23 12:03 UTC, kalpana19sharma commented on config/routes.rb
> +  delete 'users/delete_image/:id', to: 'users#delete_image', as: 'delete_image'
```suggestion
  delete 'users/images/:id', to: 'users#delete_image', as: 'delete_image' 
```

2021-03-23 12:03 UTC, kalpana19sharma commented on config/routes.rb
> +  get 'users/add_image/:id', to: 'users#add_image', as: 'add_image'
What's the need for `:id` here?

2021-03-23 12:20 UTC, Tramchandani commented on app/views/layouts/empty2.html.erb
> +</html>
ma'am this layout is for displaying images so I could not use the background I have been using for the rest of the pages as it is an image. So I did not want any background image hence this.

2021-03-23 12:29 UTC, kalpana19sharma commented on app/views/layouts/empty2.html.erb
> +</html>
So we can use conditional statement for just a small thing, right?

2021-03-23 12:31 UTC, Tramchandani commented on config/routes.rb
> +  get 'users/add_image/:id', to: 'users#add_image', as: 'add_image'
ma'am to specify the id of the user to which the image has to be attached

2021-03-23 12:54 UTC, kalpana19sharma commented on config/routes.rb
> +  get 'users/add_image/:id', to: 'users#add_image', as: 'add_image'
Then it should be like
```suggestion
  get 'users/:id/add_image', to: 'users#add_image', as: 'add_image'
```

2021-03-23 13:33 UTC, Tramchandani commented on app/views/layouts/empty2.html.erb
> +</html>
yes

2021-03-23 16:14 UTC, kalpana19sharma requested changes

2021-03-23 16:14 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +  end
Will `action_name` helper will help you removing this ambiguous logic

2021-03-24 10:22 UTC, kalpana19sharma approved these changes

2021-03-24 10:22 UTC, merged