Address
Tramchandani/gym-management-system pull request #6
Opened 2021-03-19 10:06 UTC by Tramchandani

![Screenshot from 2021-03-19 15-19-16](https://user-images.githubusercontent.com/79201195/111764017-c4b58800-88c8-11eb-82ac-ef3bceb28c3d.png)
![Screenshot from 2021-03-19 15-19-20](https://user-images.githubusercontent.com/79201195/111764021-c67f4b80-88c8-11eb-89dd-1f95f7ba5287.png)
![Screenshot from 2021-03-19 15-20-26](https://user-images.githubusercontent.com/79201195/111764029-c7b07880-88c8-11eb-80d9-545e37959ddc.png)
![Screenshot from 2021-03-19 15-20-39](https://user-images.githubusercontent.com/79201195/111764033-c8e1a580-88c8-11eb-9259-3e069fa36187.png)

2021-03-25 02:27 UTC, kalpana19sharma requested changes

2021-03-25 02:27 UTC, kalpana19sharma commented on app/controllers/addresses_controller.rb
> +    @address = Address.new
```suggestion
    @address = current_user.addresses.new
```

2021-03-25 02:27 UTC, kalpana19sharma commented on app/controllers/addresses_controller.rb
> +  end
Is this logic in other controllers as well?

2021-03-25 02:27 UTC, kalpana19sharma commented on app/controllers/addresses_controller.rb
> +    @address = Address.find_by_id(id_param[:id])
Use association to find out address

2021-03-25 02:27 UTC, kalpana19sharma commented on app/controllers/addresses_controller.rb
> +      redirect_to user_path(session[:user_id])
Use `current_user.id` for consistency

2021-03-25 02:27 UTC, kalpana19sharma commented on app/views/addresses/edit.html.erb
> +  <%= render partial: "layouts/show_notice" %>
Should this logic be in layout?

2021-03-25 02:27 UTC, kalpana19sharma commented on app/views/users/all_images.html.erb
> +<<<<<<< HEAD
??

2021-03-25 02:27 UTC, kalpana19sharma commented on app/views/users/show.html.erb
> +                  <% end %>
Should this logic be outside the conditional statement?

2021-03-25 02:27 UTC, kalpana19sharma commented on config/routes.rb
> +  delete 'users/delete_image/:id', to: 'users#delete_image', as: 'delete_image'
These routes are changes again?

2021-03-25 04:57 UTC, Tramchandani commented on app/views/addresses/edit.html.erb
> +  <%= render partial: "layouts/show_notice" %>
should I move it to shared folder?

2021-03-25 05:51 UTC, Tramchandani commented on app/controllers/addresses_controller.rb
> +  end
yes ma'am it is present in users controller too

2021-03-25 05:53 UTC, Tramchandani commented on config/routes.rb
> +  delete 'users/delete_image/:id', to: 'users#delete_image', as: 'delete_image'
ma'am I'll check what happened and fix it

2021-03-25 06:04 UTC, Tramchandani commented on app/views/users/show.html.erb
> +                  <% end %>
Ma'am actually the positioning for add new address link is changing according to each scenario. I'll refactor the code and try to remove the repetitive code.

2021-03-25 06:19 UTC, Tramchandani commented on app/controllers/addresses_controller.rb
> +  end
should I add it to application controller?

2021-03-26 02:05 UTC, kalpana19sharma commented on app/views/addresses/edit.html.erb
> +  <%= render partial: "layouts/show_notice" %>
I meant to say that should this render partial logic be in layout file?

2021-03-26 04:46 UTC, Tramchandani commented on app/views/addresses/edit.html.erb
> +  <%= render partial: "layouts/show_notice" %>
oh, yes I can move it to layout file.

2021-03-26 06:42 UTC, kalpana19sharma requested changes

2021-03-26 06:42 UTC, kalpana19sharma commented on app/controllers/addresses_controller.rb
> +    @address = current_user.addresses.find_by_id(id_param[:id])
Handle the case if address doesn't exist

2021-03-26 06:42 UTC, kalpana19sharma commented on app/controllers/addresses_controller.rb
> +  end
User need to be logged in to perform these actions, right?

2021-03-26 06:42 UTC, kalpana19sharma commented on app/views/addresses/edit.html.erb
> +    <%= render partial: "shared/address_form", locals: {form: form} %>
Use proper spaces

2021-03-26 06:42 UTC, kalpana19sharma commented on app/views/addresses/new.html.erb
> +    <%= render partial: "shared/address_form", locals: {form: form} %>
Use proper spaces.

2021-03-26 06:42 UTC, kalpana19sharma commented on app/views/users/show.html.erb
> +                    <% if address == @user.addresses.first %>
I think you can use `each_with_index` to refactor this condition.

2021-03-26 06:42 UTC, kalpana19sharma commented on app/views/users/show.html.erb
> +                    <p><%= address.house_number %>, <%= address.colony %> <%= address.street %> <%= address.city %>, <%= address.state %>
Create a helper method or instance method in model to get full address.

2021-03-26 06:51 UTC, Tramchandani commented on app/controllers/addresses_controller.rb
> +  end
Yes ma'am, I have taken the user id from session

2021-03-26 07:26 UTC, kalpana19sharma commented on app/controllers/addresses_controller.rb
> +  end
try to access address form directly by using url

2021-03-26 07:49 UTC, kalpana19sharma requested changes

2021-03-26 07:49 UTC, kalpana19sharma commented on app/controllers/addresses_controller.rb
> +    raise ActiveRecord::RecordNotFound.new('Invalid Address') if @address.nil?
This will crash your application. Redirect user to an appropriate page and show a proper flash message to user which clearly display the reason behind redirection.

2021-03-26 08:03 UTC, Tramchandani commented on app/controllers/addresses_controller.rb
> +  end
Even if the user changes the id in url to some other user's id , then also the updation and creation process of new address will be done with current user.
suppose user with user id 1 will have url: users/1/addresses/new
Now if he changes it to users/2/addresses/new and then adds the new address it will still be added to address of user 1 because user_id is being taken from session

2021-03-26 10:05 UTC, kalpana19sharma requested changes

2021-03-26 10:05 UTC, kalpana19sharma commented on app/controllers/addresses_controller.rb
> +  def error; end
I don't think you need to use an action if you are not writing routes corresponding to it. You can redirect to home page/index page of addresses instead of defining a new action.

2021-03-26 10:11 UTC, Tramchandani commented on app/controllers/addresses_controller.rb
> +  def error; end
actually if I am rendering a page directly it is giving double page render error so I have define error action so that it renders the error.html.erb page and I have written custom routes for the same as well

2021-03-26 10:15 UTC, kalpana19sharma commented on app/controllers/addresses_controller.rb
> +  def error; end
you can resolve double render error with `and return` but try not to define unnecessary actions.

2021-03-26 10:15 UTC, kalpana19sharma commented on app/controllers/addresses_controller.rb
> +  def error; end
For error message you can use flash

2021-03-26 12:22 UTC, kalpana19sharma approved these changes

2021-03-26 12:22 UTC, merged