Cart
Tramchandani/gym-management-system pull request #8
Opened 2021-03-24 12:23 UTC by Tramchandani

![Screenshot from 2021-03-24 17-51-50](https://user-images.githubusercontent.com/79201195/112309764-bf41ae80-8cc9-11eb-8264-b8ef5128a5d0.png)
![Screenshot from 2021-03-24 17-51-38](https://user-images.githubusercontent.com/79201195/112309767-c072db80-8cc9-11eb-84f7-a3236e1cdb5c.png)
![Screenshot from 2021-03-24 17-51-34](https://user-images.githubusercontent.com/79201195/112309770-c23c9f00-8cc9-11eb-8ba7-f0f3a785a1a7.png)
![Screenshot from 2021-03-24 17-51-26](https://user-images.githubusercontent.com/79201195/112309773-c36dcc00-8cc9-11eb-9073-368d0af6951b.png)

2021-03-31 11:33 UTC, kalpana19sharma commented
@Tramchandani please resolve the conflicts.

2021-03-31 12:21 UTC, kalpana19sharma requested changes

2021-03-31 12:21 UTC, kalpana19sharma commented on app/controllers/carts_controller.rb
> +    exercise = Exercise.find_by_id(exercise_id_params[:id])
Move this logic before filter

2021-03-31 12:21 UTC, kalpana19sharma commented on app/controllers/carts_controller.rb
> +    end
```suggestion
    @cart = @user.cart || @user.create_cart
```

2021-03-31 12:21 UTC, kalpana19sharma commented on app/controllers/carts_controller.rb
> +  before_action :current_cart
Rename these methods

2021-03-31 12:21 UTC, kalpana19sharma commented on app/controllers/carts_controller.rb
> +  end
I thought you had this method in application controller. And do we really need to add `before_action` filter for this?

2021-03-31 12:21 UTC, kalpana19sharma commented on app/helpers/application_helper.rb
> +    end
You can eliminate this logic by adding a after create callback in user model.

2021-03-31 12:21 UTC, kalpana19sharma commented on app/models/exercise_in_cart.rb
> +class ExerciseInCart < ApplicationRecord
Rename this model to `CartItem`

2021-03-31 12:21 UTC, kalpana19sharma commented on app/helpers/application_helper.rb
> +  def in_cart?(exercise)
Can we move this method in model?

2021-03-31 13:02 UTC, Tramchandani commented on app/controllers/carts_controller.rb
> +  end
yes ma'am it is already in application controller so it is redundant here. I will remove it.

2021-03-31 13:14 UTC, Tramchandani commented on app/models/exercise_in_cart.rb
> +class ExerciseInCart < ApplicationRecord
should I rename database table as well?

2021-03-31 13:58 UTC, kalpana19sharma commented on app/models/exercise_in_cart.rb
> +class ExerciseInCart < ApplicationRecord
yes

2021-03-31 15:15 UTC, kalpana19sharma requested changes

2021-03-31 15:15 UTC, kalpana19sharma commented on app/controllers/carts_controller.rb
> +    @exercise = Exercise.find_by_id(exercise_id_params[:id])
What if exercise is not found?

2021-03-31 15:15 UTC, kalpana19sharma commented on app/helpers/application_helper.rb
> +  end
You already have this method in application controller so better declare that as helper.

2021-03-31 15:24 UTC, Tramchandani commented on app/controllers/carts_controller.rb
> +    @exercise = Exercise.find_by_id(exercise_id_params[:id])
when user selects the exercise the exercise is added to cart and user is redirected on the same page.
SO it is not possible to change the exercise id through url.

2021-04-01 08:57 UTC, kalpana19sharma commented
@Tramchandani please resolve the conflicts.

2021-04-01 11:07 UTC, kalpana19sharma approved these changes

2021-04-01 11:07 UTC, merged