Subscribe
Tramchandani/gym-management-system pull request #9
Opened 2021-03-25 12:32 UTC by Tramchandani

![Screenshot from 2021-03-25 17-57-41](https://user-images.githubusercontent.com/79201195/112473301-2deb3e80-8d94-11eb-9852-e1b7ca6dc62a.png)
![Screenshot from 2021-03-25 17-57-17](https://user-images.githubusercontent.com/79201195/112473311-2fb50200-8d94-11eb-8c9e-8b38ad07e1ef.png)
![Screenshot from 2021-03-25 17-57-10](https://user-images.githubusercontent.com/79201195/112473313-30e62f00-8d94-11eb-8e80-2cb0d94ebd94.png)

2021-04-01 11:07 UTC, kalpana19sharma commented
@Tramchandani please resolve the conflicts.

2021-04-02 04:40 UTC, kalpana19sharma requested changes

2021-04-02 04:40 UTC, kalpana19sharma commented on app/controllers/invoices_controller.rb
> +    @invoice.user_id = current_user.cart.user_id
Do we really need to assign `user_id` manually?

2021-04-02 04:40 UTC, kalpana19sharma commented on app/controllers/invoices_controller.rb
> +      @invoice_item.save
Invoice item can be saved before invoice is saved? How does it assign invoice_id to invoice item?

2021-04-02 04:40 UTC, kalpana19sharma commented on app/models/exercise_in_cart.rb
> +  belongs_to :exercise
Only one sided associations?

2021-04-02 04:40 UTC, kalpana19sharma commented on app/views/invoices/show.html.erb
> +            <% @invoice.exercises.each do |exercise| %>
Use `each_with_index`

2021-04-02 04:40 UTC, kalpana19sharma commented on config/routes.rb
> +  get 'invoices/show/:id', to: 'invoices#show', as: 'show_invoice'
```suggestion
  get 'invoices/:id', to: 'invoices#show', as: 'show_invoice'
```

2021-04-02 06:20 UTC, Tramchandani commented on app/controllers/invoices_controller.rb
> +    @invoice.user_id = current_user.cart.user_id
no ma'am we have created invoice using association so it is not required.

2021-04-02 06:22 UTC, Tramchandani commented on app/controllers/invoices_controller.rb
> +      @invoice_item.save
I was earlier saving invoice before the for each loop but then the amount couldn't be saved. I'll call @invoice.save once before and then after the loop so that amount gets saved as well.

2021-04-02 06:30 UTC, Tramchandani commented on app/models/exercise_in_cart.rb
> +  belongs_to :exercise
actually I have changed the model name from ExerciseInCart to CartItem so this model is not used anywhere I have to remove this.

2021-04-02 06:46 UTC, kalpana19sharma approved these changes

2021-04-02 06:46 UTC, merged